// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8l0Yij0CwWEqJOgpOr7fIcO1Pum65Dp4',
    appId: '1:878660433056:web:2e32dc0c036be9ec0745c5',
    messagingSenderId: '878660433056',
    projectId: 'vize30719022',
    authDomain: 'vize30719022.firebaseapp.com',
    storageBucket: 'vize30719022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYSaUZkEQOUuu11-wRKiuHum7VJsen3g',
    appId: '1:878660433056:android:f5618a5065e0d16a0745c5',
    messagingSenderId: '878660433056',
    projectId: 'vize30719022',
    storageBucket: 'vize30719022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9mFvUBjbIs_rLBnuCJfJh6Ipa75tPJY',
    appId: '1:878660433056:ios:ec4e23c77dece74e0745c5',
    messagingSenderId: '878660433056',
    projectId: 'vize30719022',
    storageBucket: 'vize30719022.appspot.com',
    iosClientId: '878660433056-cch909v12gtqbp3tfkbrku5kotom5f0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9mFvUBjbIs_rLBnuCJfJh6Ipa75tPJY',
    appId: '1:878660433056:ios:ec4e23c77dece74e0745c5',
    messagingSenderId: '878660433056',
    projectId: 'vize30719022',
    storageBucket: 'vize30719022.appspot.com',
    iosClientId: '878660433056-cch909v12gtqbp3tfkbrku5kotom5f0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
